window.FLEET_DATA = [
  {
    "nn": "01",
    "key": "haulage-trucking",
    "loc": "de",
    "name": "Haulage / trucking",
    "company": "Rheinland Schwertransport & Logistik GmbH",
    "legalForm": "GmbH",
    "city": "Köln",
    "fleet": 7,
    "file": "01-haulage-trucking.de.json",
    "sizeKB": 7466.0,
    "total": 242,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 7,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "01",
    "key": "haulage-trucking",
    "loc": "en",
    "name": "Haulage / trucking",
    "company": "Pennine Freight & Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 38,
    "file": "01-haulage-trucking.en.json",
    "sizeKB": 7084.0,
    "total": 250,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 7,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 11,
      "customers": 6,
      "locations": 10,
      "workOrders": 14,
      "routes": 14,
      "stops": 36,
      "assignments": 14,
      "telemetryReadings": 47,
      "events": 16,
      "notes": 14,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "01",
    "key": "haulage-trucking",
    "loc": "sv",
    "name": "Haulage / trucking",
    "company": "Nordström Frakt & Logistik AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 7,
    "file": "01-haulage-trucking.sv.json",
    "sizeKB": 6745.0,
    "total": 253,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 7,
      "trackedObjects": 8,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 11,
      "workOrders": 14,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "02",
    "key": "courier-last-mile",
    "loc": "de",
    "name": "Courier, parcel & last-mile",
    "company": "IsarKurier Stadtlogistik GmbH",
    "legalForm": "GmbH",
    "city": "Munchen",
    "fleet": 9,
    "file": "02-courier-last-mile.de.json",
    "sizeKB": 8034.0,
    "total": 255,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 34,
      "assignments": 13,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "02",
    "key": "courier-last-mile",
    "loc": "en",
    "name": "Courier, parcel & last-mile",
    "company": "Pennine Parcel Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 7,
    "file": "02-courier-last-mile.en.json",
    "sizeKB": 6718.0,
    "total": 280,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 7,
      "trackedObjects": 8,
      "drivers": 7,
      "driverCertifications": 13,
      "customers": 6,
      "locations": 11,
      "workOrders": 14,
      "routes": 14,
      "stops": 40,
      "assignments": 14,
      "telemetryReadings": 55,
      "events": 26,
      "notes": 15,
      "documents": 16,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "02",
    "key": "courier-last-mile",
    "loc": "sv",
    "name": "Courier, parcel & last-mile",
    "company": "Mälardalen Bud & Paketservice AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 9,
    "file": "02-courier-last-mile.sv.json",
    "sizeKB": 8041.0,
    "total": 263,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 39,
      "assignments": 14,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "03",
    "key": "moving-removal",
    "loc": "de",
    "name": "Moving & removal",
    "company": "Hanseatische Möbeltransport & Umzugsservice GmbH",
    "legalForm": "GmbH",
    "city": "Hamburg",
    "fleet": 7,
    "file": "03-moving-removal.de.json",
    "sizeKB": 7516.0,
    "total": 266,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 7,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 15,
      "workOrders": 13,
      "routes": 14,
      "stops": 31,
      "assignments": 15,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 14,
      "documents": 17,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "03",
    "key": "moving-removal",
    "loc": "en",
    "name": "Moving & removal",
    "company": "Britannia Crown Removals & Storage Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 8,
    "file": "03-moving-removal.en.json",
    "sizeKB": 7471.0,
    "total": 260,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 8,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 14,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "03",
    "key": "moving-removal",
    "loc": "sv",
    "name": "Moving & removal",
    "company": "Mälarflytt Stockholm AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 7,
    "file": "03-moving-removal.sv.json",
    "sizeKB": 9090.0,
    "total": 258,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 7,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 47,
      "events": 17,
      "notes": 13,
      "documents": 22,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "04",
    "key": "freight-forwarder-3pl",
    "loc": "de",
    "name": "Freight forwarder / 3PL",
    "company": "Hanseatic Forwarding & Contract Logistics GmbH",
    "legalForm": "GmbH",
    "city": "Hamburg",
    "fleet": 8,
    "file": "04-freight-forwarder-3pl.de.json",
    "sizeKB": 7504.0,
    "total": 248,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 8,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 13,
      "workOrders": 13,
      "routes": 13,
      "stops": 28,
      "assignments": 13,
      "telemetryReadings": 43,
      "events": 17,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "04",
    "key": "freight-forwarder-3pl",
    "loc": "en",
    "name": "Freight forwarder / 3PL",
    "company": "Albion Gateway Freight Services Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 24,
    "file": "04-freight-forwarder-3pl.en.json",
    "sizeKB": 8025.0,
    "total": 276,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 10,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 15,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 16,
      "stops": 33,
      "assignments": 16,
      "telemetryReadings": 53,
      "events": 17,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "04",
    "key": "freight-forwarder-3pl",
    "loc": "sv",
    "name": "Freight forwarder / 3PL",
    "company": "Nordväst Spedition & Logistik AB",
    "legalForm": "AB",
    "city": "Helsingborg",
    "fleet": 9,
    "file": "04-freight-forwarder-3pl.sv.json",
    "sizeKB": 8014.0,
    "total": 260,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 14,
      "stops": 31,
      "assignments": 14,
      "telemetryReadings": 50,
      "events": 16,
      "notes": 13,
      "documents": 20,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "05",
    "key": "bus-coach",
    "loc": "de",
    "name": "Bus & coach operator",
    "company": "Isartal Reise- und Verkehrsbetriebe GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "05-bus-coach.de.json",
    "sizeKB": 7120.0,
    "total": 251,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 13,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 34,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "05",
    "key": "bus-coach",
    "loc": "en",
    "name": "Bus & coach operator",
    "company": "Calder Valley Coaches Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 8,
    "file": "05-bus-coach.en.json",
    "sizeKB": 7644.0,
    "total": 275,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 15,
      "stops": 40,
      "assignments": 15,
      "telemetryReadings": 49,
      "events": 18,
      "notes": 15,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "05",
    "key": "bus-coach",
    "loc": "sv",
    "name": "Bus & coach operator",
    "company": "Smålandstrafiken Buss & Coach AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 9,
    "file": "05-bus-coach.sv.json",
    "sizeKB": 6370.0,
    "total": 266,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 37,
      "assignments": 15,
      "telemetryReadings": 51,
      "events": 18,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "06",
    "key": "taxi-ridehail",
    "loc": "de",
    "name": "Taxi, ride-hail & limousine",
    "company": "Isar Funk Taxi- und Mietwagen GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 11,
    "file": "06-taxi-ridehail.de.json",
    "sizeKB": 7638.0,
    "total": 263,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 11,
      "trackedObjects": 9,
      "drivers": 10,
      "driverCertifications": 17,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 14,
      "stops": 31,
      "assignments": 14,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "06",
    "key": "taxi-ridehail",
    "loc": "en",
    "name": "Taxi, ride-hail & limousine",
    "company": "Meridian Cars & Chauffeur Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 38,
    "file": "06-taxi-ridehail.en.json",
    "sizeKB": 6524.0,
    "total": 237,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 42,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "06",
    "key": "taxi-ridehail",
    "loc": "sv",
    "name": "Taxi, ride-hail & limousine",
    "company": "Götaland Taxi & Limousine AB",
    "legalForm": "AB",
    "city": "Göteborg",
    "fleet": 9,
    "file": "06-taxi-ridehail.sv.json",
    "sizeKB": 5994.0,
    "total": 245,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 13,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "07",
    "key": "vehicle-rental-leasing",
    "loc": "de",
    "name": "Vehicle rental & leasing",
    "company": "RheinAuto Vermietung & Leasing GmbH",
    "legalForm": "GmbH",
    "city": "Köln",
    "fleet": 11,
    "file": "07-vehicle-rental-leasing.de.json",
    "sizeKB": 6741.0,
    "total": 256,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 28,
      "assignments": 13,
      "telemetryReadings": 51,
      "events": 18,
      "notes": 14,
      "documents": 16,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "07",
    "key": "vehicle-rental-leasing",
    "loc": "en",
    "name": "Vehicle rental & leasing",
    "company": "Albion Vehicle Hire & Leasing Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 11,
    "file": "07-vehicle-rental-leasing.en.json",
    "sizeKB": 6368.0,
    "total": 241,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 11,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 28,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "07",
    "key": "vehicle-rental-leasing",
    "loc": "sv",
    "name": "Vehicle rental & leasing",
    "company": "Nordström Biluthyrning & Leasing AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 11,
    "file": "07-vehicle-rental-leasing.sv.json",
    "sizeKB": 6180.0,
    "total": 254,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 8,
      "drivers": 9,
      "driverCertifications": 13,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "08",
    "key": "construction",
    "loc": "de",
    "name": "Construction (mixed plant)",
    "company": "Donaustein Tief- und Maschinenbau GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 11,
    "file": "08-construction.de.json",
    "sizeKB": 7848.0,
    "total": 262,
    "counts": {
      "vehicleTypes": 9,
      "vehicles": 11,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 34,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "08",
    "key": "construction",
    "loc": "en",
    "name": "Construction (mixed plant)",
    "company": "Trent Valley Plant & Civils Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 9,
    "file": "08-construction.en.json",
    "sizeKB": 7483.0,
    "total": 262,
    "counts": {
      "vehicleTypes": 8,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 15,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 18,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 7,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "08",
    "key": "construction",
    "loc": "sv",
    "name": "Construction (mixed plant)",
    "company": "Nordvik Bygg & Anläggning AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 11,
    "file": "08-construction.sv.json",
    "sizeKB": 8938.0,
    "total": 259,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 11,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 15,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 14,
      "stops": 29,
      "assignments": 14,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 12,
      "documents": 21,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "09",
    "key": "mining-quarrying",
    "loc": "de",
    "name": "Mining & quarrying",
    "company": "Frankenwald Hartsteinwerke GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 11,
    "file": "09-mining-quarrying.de.json",
    "sizeKB": 7856.0,
    "total": 277,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 11,
      "trackedObjects": 9,
      "drivers": 9,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 14,
      "stops": 38,
      "assignments": 14,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 13,
      "documents": 19,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "09",
    "key": "mining-quarrying",
    "loc": "en",
    "name": "Mining & quarrying",
    "company": "Pennine Aggregates & Quarrying Ltd",
    "legalForm": "Ltd",
    "city": "Sheffield",
    "fleet": 32,
    "file": "09-mining-quarrying.en.json",
    "sizeKB": 7494.0,
    "total": 273,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 10,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 37,
      "assignments": 16,
      "telemetryReadings": 53,
      "events": 17,
      "notes": 14,
      "documents": 17,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "09",
    "key": "mining-quarrying",
    "loc": "sv",
    "name": "Mining & quarrying",
    "company": "Vätterbygdens Bergtäkt & Ballast AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 12,
    "file": "09-mining-quarrying.sv.json",
    "sizeKB": 7305.0,
    "total": 262,
    "counts": {
      "vehicleTypes": 9,
      "vehicles": 12,
      "trackedObjects": 8,
      "drivers": 9,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 14,
      "stops": 34,
      "assignments": 14,
      "telemetryReadings": 50,
      "events": 16,
      "notes": 13,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "10",
    "key": "oil-gas-field",
    "loc": "de",
    "name": "Oil, gas & energy field",
    "company": "Emsland Energie Felddienste GmbH",
    "legalForm": "GmbH",
    "city": "Lingen (Ems)",
    "fleet": 8,
    "file": "10-oil-gas-field.de.json",
    "sizeKB": 8379.0,
    "total": 258,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 15,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 33,
      "assignments": 13,
      "telemetryReadings": 46,
      "events": 18,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "10",
    "key": "oil-gas-field",
    "loc": "en",
    "name": "Oil, gas & energy field",
    "company": "Caledonian Wellsite Field Services Ltd",
    "legalForm": "Ltd",
    "city": "Aberdeen",
    "fleet": 41,
    "file": "10-oil-gas-field.en.json",
    "sizeKB": 7005.0,
    "total": 266,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 18,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 37,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "10",
    "key": "oil-gas-field",
    "loc": "sv",
    "name": "Oil, gas & energy field",
    "company": "Nordkraft Fältservice & Energilogistik AB",
    "legalForm": "AB",
    "city": "Göteborg",
    "fleet": 9,
    "file": "10-oil-gas-field.sv.json",
    "sizeKB": 6320.0,
    "total": 254,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 49,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "11",
    "key": "forestry-timber",
    "loc": "de",
    "name": "Forestry & timber haulage",
    "company": "Schwarzwald Rundholz- und Forstlogistik GmbH",
    "legalForm": "GmbH",
    "city": "Freiburg im Breisgau",
    "fleet": 9,
    "file": "11-forestry-timber.de.json",
    "sizeKB": 8418.0,
    "total": 273,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 11,
      "drivers": 8,
      "driverCertifications": 18,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 14,
      "stops": 36,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 19,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "11",
    "key": "forestry-timber",
    "loc": "en",
    "name": "Forestry & timber haulage",
    "company": "Caledon Timber Haulage Ltd",
    "legalForm": "Ltd",
    "city": "Glasgow",
    "fleet": 7,
    "file": "11-forestry-timber.en.json",
    "sizeKB": 6716.0,
    "total": 251,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 7,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 15,
      "customers": 7,
      "locations": 10,
      "workOrders": 13,
      "routes": 14,
      "stops": 30,
      "assignments": 15,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 14,
      "documents": 16,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "11",
    "key": "forestry-timber",
    "loc": "sv",
    "name": "Forestry & timber haulage",
    "company": "Smålands Skog & Timmertransport AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 9,
    "file": "11-forestry-timber.sv.json",
    "sizeKB": 7491.0,
    "total": 269,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 9,
      "driverCertifications": 15,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 14,
      "stops": 30,
      "assignments": 14,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 15,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "12",
    "key": "plant-equipment-hire",
    "loc": "de",
    "name": "Plant & equipment hire",
    "company": "RheinMietTechnik Baumaschinenvermietung GmbH",
    "legalForm": "GmbH",
    "city": "Köln",
    "fleet": 11,
    "file": "12-plant-equipment-hire.de.json",
    "sizeKB": 6569.0,
    "total": 251,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 11,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "12",
    "key": "plant-equipment-hire",
    "loc": "en",
    "name": "Plant & equipment hire",
    "company": "Pennine Plant & Tool Hire Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 9,
    "file": "12-plant-equipment-hire.en.json",
    "sizeKB": 6911.0,
    "total": 245,
    "counts": {
      "vehicleTypes": 9,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "12",
    "key": "plant-equipment-hire",
    "loc": "sv",
    "name": "Plant & equipment hire",
    "company": "Svealands Maskinuthyrning AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 10,
    "file": "12-plant-equipment-hire.sv.json",
    "sizeKB": 7839.0,
    "total": 253,
    "counts": {
      "vehicleTypes": 9,
      "vehicles": 10,
      "trackedObjects": 8,
      "drivers": 7,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 13,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "13",
    "key": "plumbing-hvac",
    "loc": "de",
    "name": "Plumbing / electrical / HVAC",
    "company": "Isar Sanitär & Klimatechnik GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "13-plumbing-hvac.de.json",
    "sizeKB": 6657.0,
    "total": 252,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "13",
    "key": "plumbing-hvac",
    "loc": "en",
    "name": "Plumbing / electrical / HVAC",
    "company": "Pennine Mechanical & Heating Services Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 8,
    "file": "13-plumbing-hvac.en.json",
    "sizeKB": 7095.0,
    "total": 244,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 16,
      "notes": 13,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "13",
    "key": "plumbing-hvac",
    "loc": "sv",
    "name": "Plumbing / electrical / HVAC",
    "company": "Bergström Rör & El AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 9,
    "file": "13-plumbing-hvac.sv.json",
    "sizeKB": 7270.0,
    "total": 266,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 7,
      "locations": 14,
      "workOrders": 15,
      "routes": 15,
      "stops": 31,
      "assignments": 15,
      "telemetryReadings": 47,
      "events": 18,
      "notes": 14,
      "documents": 17,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "14",
    "key": "telecom-utility",
    "loc": "de",
    "name": "Telecom & utility maintenance",
    "company": "Rheinland NetzService GmbH",
    "legalForm": "GmbH",
    "city": "Köln",
    "fleet": 9,
    "file": "14-telecom-utility.de.json",
    "sizeKB": 8378.0,
    "total": 267,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 9,
      "driverCertifications": 18,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 34,
      "assignments": 13,
      "telemetryReadings": 49,
      "events": 18,
      "notes": 13,
      "documents": 20,
      "fieldDefinitions": 12,
      "inspections": 7,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "14",
    "key": "telecom-utility",
    "loc": "en",
    "name": "Telecom & utility maintenance",
    "company": "Pennine Networks & Utility Maintenance Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 9,
    "file": "14-telecom-utility.en.json",
    "sizeKB": 6940.0,
    "total": 257,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 9,
      "driverCertifications": 15,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 32,
      "assignments": 13,
      "telemetryReadings": 50,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "14",
    "key": "telecom-utility",
    "loc": "sv",
    "name": "Telecom & utility maintenance",
    "company": "NordNät Fält & Underhåll AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 9,
    "file": "14-telecom-utility.sv.json",
    "sizeKB": 6916.0,
    "total": 256,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 7,
      "locations": 11,
      "workOrders": 14,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 14,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "15",
    "key": "landscaping-grounds",
    "loc": "de",
    "name": "Landscaping & grounds",
    "company": "GrünWerk München Garten- und Landschaftsbau GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "15-landscaping-grounds.de.json",
    "sizeKB": 7527.0,
    "total": 260,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 8,
      "trackedObjects": 8,
      "drivers": 9,
      "driverCertifications": 15,
      "customers": 7,
      "locations": 13,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 13,
      "telemetryReadings": 46,
      "events": 18,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "15",
    "key": "landscaping-grounds",
    "loc": "en",
    "name": "Landscaping & grounds",
    "company": "Greenfell Grounds Maintenance Ltd",
    "legalForm": "Ltd",
    "city": "Bristol",
    "fleet": 9,
    "file": "15-landscaping-grounds.en.json",
    "sizeKB": 8064.0,
    "total": 260,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 12,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 17,
      "customers": 6,
      "locations": 9,
      "workOrders": 13,
      "routes": 14,
      "stops": 34,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 16,
      "notes": 14,
      "documents": 19,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "15",
    "key": "landscaping-grounds",
    "loc": "sv",
    "name": "Landscaping & grounds",
    "company": "Västkustens Grön- och Markskötsel AB",
    "legalForm": "AB",
    "city": "Göteborg",
    "fleet": 9,
    "file": "15-landscaping-grounds.sv.json",
    "sizeKB": 8808.0,
    "total": 274,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 9,
      "driverCertifications": 18,
      "customers": 7,
      "locations": 13,
      "workOrders": 13,
      "routes": 14,
      "stops": 35,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 18,
      "notes": 13,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "16",
    "key": "pest-cleaning-facility",
    "loc": "de",
    "name": "Pest control / cleaning / facility",
    "company": "BavariaPro Schädlingsbekämpfung & Gebäudeservice GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "16-pest-cleaning-facility.de.json",
    "sizeKB": 7258.0,
    "total": 268,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 10,
      "workOrders": 14,
      "routes": 14,
      "stops": 41,
      "assignments": 14,
      "telemetryReadings": 51,
      "events": 17,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "16",
    "key": "pest-cleaning-facility",
    "loc": "en",
    "name": "Pest control / cleaning / facility",
    "company": "Sentinel Pest & Facility Services Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 9,
    "file": "16-pest-cleaning-facility.en.json",
    "sizeKB": 7495.0,
    "total": 249,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 7,
      "trackedObjects": 8,
      "drivers": 7,
      "driverCertifications": 21,
      "customers": 6,
      "locations": 10,
      "workOrders": 12,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 47,
      "events": 16,
      "notes": 13,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "16",
    "key": "pest-cleaning-facility",
    "loc": "sv",
    "name": "Pest control / cleaning / facility",
    "company": "Nordström Skadedjur & Fastighetsservice AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 9,
    "file": "16-pest-cleaning-facility.sv.json",
    "sizeKB": 6871.0,
    "total": 266,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 10,
      "driverCertifications": 16,
      "customers": 8,
      "locations": 14,
      "workOrders": 14,
      "routes": 14,
      "stops": 30,
      "assignments": 14,
      "telemetryReadings": 48,
      "events": 18,
      "notes": 14,
      "documents": 17,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "17",
    "key": "coldchain-food",
    "loc": "de",
    "name": "Cold-chain food & beverage",
    "company": "FrischeKette Süd Lebensmittellogistik GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "17-coldchain-food.de.json",
    "sizeKB": 8166.0,
    "total": 280,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 10,
      "driverCertifications": 21,
      "customers": 8,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 35,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 19,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 15,
      "inspections": 6,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "17",
    "key": "coldchain-food",
    "loc": "en",
    "name": "Cold-chain food & beverage",
    "company": "Frostmere Chilled Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 34,
    "file": "17-coldchain-food.en.json",
    "sizeKB": 7838.0,
    "total": 267,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 15,
      "customers": 7,
      "locations": 11,
      "workOrders": 14,
      "routes": 13,
      "stops": 33,
      "assignments": 14,
      "telemetryReadings": 54,
      "events": 17,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "17",
    "key": "coldchain-food",
    "loc": "sv",
    "name": "Cold-chain food & beverage",
    "company": "Frostvägen Kyllogistik AB",
    "legalForm": "AB",
    "city": "Norrköping",
    "fleet": 9,
    "file": "17-coldchain-food.sv.json",
    "sizeKB": 5538.0,
    "total": 238,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 7,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 16,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "18",
    "key": "grocery-retail",
    "loc": "de",
    "name": "Grocery & retail distribution",
    "company": "Rheinland Frischelogistik GmbH",
    "legalForm": "GmbH",
    "city": "Köln",
    "fleet": 9,
    "file": "18-grocery-retail.de.json",
    "sizeKB": 8590.0,
    "total": 270,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 6,
      "locations": 13,
      "workOrders": 13,
      "routes": 13,
      "stops": 37,
      "assignments": 13,
      "telemetryReadings": 50,
      "events": 17,
      "notes": 13,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "18",
    "key": "grocery-retail",
    "loc": "en",
    "name": "Grocery & retail distribution",
    "company": "Pennine Grocery Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 9,
    "file": "18-grocery-retail.en.json",
    "sizeKB": 7461.0,
    "total": 279,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 11,
      "drivers": 10,
      "driverCertifications": 16,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 37,
      "assignments": 14,
      "telemetryReadings": 52,
      "events": 17,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 14,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "18",
    "key": "grocery-retail",
    "loc": "sv",
    "name": "Grocery & retail distribution",
    "company": "Nordlund Livsmedelslogistik AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 9,
    "file": "18-grocery-retail.sv.json",
    "sizeKB": 8596.0,
    "total": 270,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 6,
      "locations": 13,
      "workOrders": 13,
      "routes": 13,
      "stops": 37,
      "assignments": 13,
      "telemetryReadings": 50,
      "events": 17,
      "notes": 13,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "19",
    "key": "vending-route",
    "loc": "de",
    "name": "Wholesale & vending route",
    "company": "Isar Automaten- und Versorgungsservice GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 8,
    "file": "19-vending-route.de.json",
    "sizeKB": 8599.0,
    "total": 265,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 8,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 6,
      "locations": 9,
      "workOrders": 13,
      "routes": 15,
      "stops": 32,
      "assignments": 15,
      "telemetryReadings": 53,
      "events": 17,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "19",
    "key": "vending-route",
    "loc": "en",
    "name": "Wholesale & vending route",
    "company": "Pennine Refreshment Services Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 9,
    "file": "19-vending-route.en.json",
    "sizeKB": 8210.0,
    "total": 254,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 7,
      "trackedObjects": 8,
      "drivers": 7,
      "driverCertifications": 16,
      "customers": 6,
      "locations": 9,
      "workOrders": 13,
      "routes": 15,
      "stops": 31,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "19",
    "key": "vending-route",
    "loc": "sv",
    "name": "Wholesale & vending route",
    "company": "Mälardalens Automatservice AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 8,
    "file": "19-vending-route.sv.json",
    "sizeKB": 6547.0,
    "total": 244,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 8,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 30,
      "assignments": 14,
      "telemetryReadings": 44,
      "events": 16,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "20",
    "key": "waste-recycling",
    "loc": "de",
    "name": "Waste collection & recycling",
    "company": "RheinMain Entsorgung & Wertstoff GmbH",
    "legalForm": "GmbH",
    "city": "Frankfurt am Main",
    "fleet": 12,
    "file": "20-waste-recycling.de.json",
    "sizeKB": 6766.0,
    "total": 275,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 12,
      "trackedObjects": 13,
      "drivers": 10,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 14,
      "stops": 38,
      "assignments": 14,
      "telemetryReadings": 52,
      "events": 16,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "20",
    "key": "waste-recycling",
    "loc": "en",
    "name": "Waste collection & recycling",
    "company": "Pennine Waste & Recycling Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 11,
    "file": "20-waste-recycling.en.json",
    "sizeKB": 6751.0,
    "total": 267,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 12,
      "drivers": 10,
      "driverCertifications": 16,
      "customers": 8,
      "locations": 14,
      "workOrders": 14,
      "routes": 14,
      "stops": 31,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "20",
    "key": "waste-recycling",
    "loc": "sv",
    "name": "Waste collection & recycling",
    "company": "Götaland Återvinning & Renhållning AB",
    "legalForm": "AB",
    "city": "Göteborg",
    "fleet": 11,
    "file": "20-waste-recycling.sv.json",
    "sizeKB": 6672.0,
    "total": 264,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 16,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 14,
      "stops": 33,
      "assignments": 14,
      "telemetryReadings": 47,
      "events": 16,
      "notes": 14,
      "documents": 16,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "21",
    "key": "farm-agri",
    "loc": "de",
    "name": "Farm & agricultural cooperative",
    "company": "Maschinenring Niederbayern Agrar eG",
    "legalForm": "eG (eingetragene Genossenschaft)",
    "city": "Landshut",
    "fleet": 9,
    "file": "21-farm-agri.de.json",
    "sizeKB": 6403.0,
    "total": 265,
    "counts": {
      "vehicleTypes": 8,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 19,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 15,
      "stops": 32,
      "assignments": 15,
      "telemetryReadings": 51,
      "events": 16,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "21",
    "key": "farm-agri",
    "loc": "en",
    "name": "Farm & agricultural cooperative",
    "company": "Vale of York Farmers' Co-operative Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 9,
    "file": "21-farm-agri.en.json",
    "sizeKB": 9323.0,
    "total": 280,
    "counts": {
      "vehicleTypes": 8,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 19,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 15,
      "stops": 32,
      "assignments": 15,
      "telemetryReadings": 50,
      "events": 18,
      "notes": 15,
      "documents": 22,
      "fieldDefinitions": 14,
      "inspections": 8,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "21",
    "key": "farm-agri",
    "loc": "sv",
    "name": "Farm & agricultural cooperative",
    "company": "Vätterbygdens Maskinring ek. för.",
    "legalForm": "Ekonomisk förening (driver maskindelen via Vätterbygdens Maskin AB)",
    "city": "Jönköping",
    "fleet": 9,
    "file": "21-farm-agri.sv.json",
    "sizeKB": 9682.0,
    "total": 279,
    "counts": {
      "vehicleTypes": 8,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 19,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 15,
      "stops": 32,
      "assignments": 15,
      "telemetryReadings": 50,
      "events": 18,
      "notes": 14,
      "documents": 22,
      "fieldDefinitions": 14,
      "inspections": 8,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "22",
    "key": "livestock-produce",
    "loc": "de",
    "name": "Livestock & produce hauler",
    "company": "Niederbayern Vieh- & Agrartransporte GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "22-livestock-produce.de.json",
    "sizeKB": 6340.0,
    "total": 276,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 10,
      "driverCertifications": 22,
      "customers": 8,
      "locations": 13,
      "workOrders": 13,
      "routes": 13,
      "stops": 36,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 19,
      "notes": 14,
      "documents": 16,
      "fieldDefinitions": 16,
      "inspections": 6,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "22",
    "key": "livestock-produce",
    "loc": "en",
    "name": "Livestock & produce hauler",
    "company": "Pennine Livestock & Produce Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 7,
    "file": "22-livestock-produce.en.json",
    "sizeKB": 9330.0,
    "total": 259,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 7,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 18,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 18,
      "notes": 14,
      "documents": 22,
      "fieldDefinitions": 14,
      "inspections": 8,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "22",
    "key": "livestock-produce",
    "loc": "sv",
    "name": "Livestock & produce hauler",
    "company": "Smålandsbygdens Djur- och Lantbrukstransport AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 9,
    "file": "22-livestock-produce.sv.json",
    "sizeKB": 5951.0,
    "total": 259,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 18,
      "customers": 7,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 54,
      "events": 17,
      "notes": 14,
      "documents": 15,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "23",
    "key": "emergency-services",
    "loc": "de",
    "name": "Emergency services",
    "company": "Isar Rettungs- und Sicherheitsdienst gemeinnuetzige GmbH",
    "legalForm": "gGmbH",
    "city": "Muenchen",
    "fleet": 11,
    "file": "23-emergency-services.de.json",
    "sizeKB": 6401.0,
    "total": 243,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 13,
      "customers": 7,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 15,
      "telemetryReadings": 44,
      "events": 16,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "23",
    "key": "emergency-services",
    "loc": "en",
    "name": "Emergency services",
    "company": "Severn & Trent Emergency Fleet Services Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 9,
    "file": "23-emergency-services.en.json",
    "sizeKB": 6567.0,
    "total": 249,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 35,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "23",
    "key": "emergency-services",
    "loc": "sv",
    "name": "Emergency services",
    "company": "Mälardalens Beredskap & Räddning AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 11,
    "file": "23-emergency-services.sv.json",
    "sizeKB": 7804.0,
    "total": 291,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 10,
      "drivers": 11,
      "driverCertifications": 21,
      "customers": 8,
      "locations": 15,
      "workOrders": 14,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 56,
      "events": 20,
      "notes": 14,
      "documents": 19,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "24",
    "key": "nemt-patient-transport",
    "loc": "de",
    "name": "Non-emergency / patient transport",
    "company": "VitalFahrt Krankentransport & Patientenfahrdienst GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 8,
    "file": "24-nemt-patient-transport.de.json",
    "sizeKB": 6124.0,
    "total": 242,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 7,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 47,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "24",
    "key": "nemt-patient-transport",
    "loc": "en",
    "name": "Non-emergency / patient transport",
    "company": "Albion Patient Transport Services Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 9,
    "file": "24-nemt-patient-transport.en.json",
    "sizeKB": 8413.0,
    "total": 287,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 18,
      "customers": 7,
      "locations": 12,
      "workOrders": 15,
      "routes": 16,
      "stops": 39,
      "assignments": 16,
      "telemetryReadings": 50,
      "events": 20,
      "notes": 14,
      "documents": 20,
      "fieldDefinitions": 14,
      "inspections": 7,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "24",
    "key": "nemt-patient-transport",
    "loc": "sv",
    "name": "Non-emergency / patient transport",
    "company": "Vårdresor Mälardalen AB",
    "legalForm": "AB",
    "city": "Uppsala",
    "fleet": 9,
    "file": "24-nemt-patient-transport.sv.json",
    "sizeKB": 6304.0,
    "total": 267,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 13,
      "workOrders": 14,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 56,
      "events": 17,
      "notes": 14,
      "documents": 15,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "25",
    "key": "airport-gse-shuttle",
    "loc": "de",
    "name": "Airport ground services & shuttle",
    "company": "AeroServ Bodenverkehrsdienste Muenchen GmbH",
    "legalForm": "GmbH",
    "city": "Muenchen",
    "fleet": 14,
    "file": "25-airport-gse-shuttle.de.json",
    "sizeKB": 6613.0,
    "total": 257,
    "counts": {
      "vehicleTypes": 8,
      "vehicles": 11,
      "trackedObjects": 8,
      "drivers": 9,
      "driverCertifications": 15,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 33,
      "assignments": 16,
      "telemetryReadings": 42,
      "events": 16,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "25",
    "key": "airport-gse-shuttle",
    "loc": "en",
    "name": "Airport ground services & shuttle",
    "company": "Albion Apron Services Ltd",
    "legalForm": "Ltd",
    "city": "London",
    "fleet": 16,
    "file": "25-airport-gse-shuttle.en.json",
    "sizeKB": 6567.0,
    "total": 248,
    "counts": {
      "vehicleTypes": 9,
      "vehicles": 12,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 14,
      "telemetryReadings": 42,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "25",
    "key": "airport-gse-shuttle",
    "loc": "sv",
    "name": "Airport ground services & shuttle",
    "company": "Arlanda Ramp & Shuttle Service AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 11,
    "file": "25-airport-gse-shuttle.sv.json",
    "sizeKB": 6570.0,
    "total": 266,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 11,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 35,
      "assignments": 15,
      "telemetryReadings": 51,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "26",
    "key": "funeral-livery",
    "loc": "de",
    "name": "Funeral home / livery",
    "company": "Pietät Rosengarten Bestattungen GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "26-funeral-livery.de.json",
    "sizeKB": 7130.0,
    "total": 251,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 16,
      "telemetryReadings": 44,
      "events": 18,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "26",
    "key": "funeral-livery",
    "loc": "en",
    "name": "Funeral home / livery",
    "company": "Wakefield & Sons Funeral Directors Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 9,
    "file": "26-funeral-livery.en.json",
    "sizeKB": 6756.0,
    "total": 245,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 16,
      "telemetryReadings": 42,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "26",
    "key": "funeral-livery",
    "loc": "sv",
    "name": "Funeral home / livery",
    "company": "Smålands Begravningsbyrå & Ceremonibilar AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 9,
    "file": "26-funeral-livery.sv.json",
    "sizeKB": 6774.0,
    "total": 245,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 16,
      "telemetryReadings": 42,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "27",
    "key": "municipal-govt",
    "loc": "de",
    "name": "Municipality / local government",
    "company": "Stadtbetriebe Rhein-Erft Bauhof & Stadtreinigung GmbH",
    "legalForm": "GmbH (kommunaler Eigenbetrieb in privatrechtlicher Form)",
    "city": "Koeln",
    "fleet": 11,
    "file": "27-municipal-govt.de.json",
    "sizeKB": 7349.0,
    "total": 282,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 12,
      "drivers": 11,
      "driverCertifications": 18,
      "customers": 8,
      "locations": 16,
      "workOrders": 14,
      "routes": 14,
      "stops": 38,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 13,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "27",
    "key": "municipal-govt",
    "loc": "en",
    "name": "Municipality / local government",
    "company": "Calderbrook Borough Council Fleet & Highways Services",
    "legalForm": "Local Authority (in-house Direct Labour Organisation)",
    "city": "Leeds",
    "fleet": 11,
    "file": "27-municipal-govt.en.json",
    "sizeKB": 7346.0,
    "total": 282,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 12,
      "drivers": 11,
      "driverCertifications": 18,
      "customers": 8,
      "locations": 16,
      "workOrders": 14,
      "routes": 14,
      "stops": 38,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 13,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "27",
    "key": "municipal-govt",
    "loc": "sv",
    "name": "Municipality / local government",
    "company": "Örebro Stadsdrift AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 13,
    "file": "27-municipal-govt.sv.json",
    "sizeKB": 5748.0,
    "total": 267,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 13,
      "trackedObjects": 13,
      "drivers": 11,
      "driverCertifications": 18,
      "customers": 8,
      "locations": 13,
      "workOrders": 14,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 43,
      "events": 16,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "28",
    "key": "schools-universities",
    "loc": "de",
    "name": "Schools & universities",
    "company": "Rheinland Schul- und Campusverkehr GmbH",
    "legalForm": "GmbH",
    "city": "Köln",
    "fleet": 8,
    "file": "28-schools-universities.de.json",
    "sizeKB": 8057.0,
    "total": 254,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 15,
      "customers": 6,
      "locations": 13,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 46,
      "events": 18,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "28",
    "key": "schools-universities",
    "loc": "en",
    "name": "Schools & universities",
    "company": "Pennine Scholar Transport Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 9,
    "file": "28-schools-universities.en.json",
    "sizeKB": 5936.0,
    "total": 250,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 18,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 16,
      "notes": 12,
      "documents": 14,
      "fieldDefinitions": 14,
      "inspections": 7,
      "maintenanceJobs": 6
    }
  },
  {
    "nn": "28",
    "key": "schools-universities",
    "loc": "sv",
    "name": "Schools & universities",
    "company": "Vätterbygdens Skolskjuts & Campusbuss AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 8,
    "file": "28-schools-universities.sv.json",
    "sizeKB": 6772.0,
    "total": 270,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 17,
      "customers": 6,
      "locations": 13,
      "workOrders": 13,
      "routes": 15,
      "stops": 33,
      "assignments": 16,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 14,
      "inspections": 7,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "29",
    "key": "postal-agency",
    "loc": "de",
    "name": "Postal service / agency",
    "company": "Bundespost Logistik & Zustelldienst GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "29-postal-agency.de.json",
    "sizeKB": 6199.0,
    "total": 256,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 9,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 14,
      "workOrders": 13,
      "routes": 13,
      "stops": 34,
      "assignments": 13,
      "telemetryReadings": 54,
      "events": 16,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "29",
    "key": "postal-agency",
    "loc": "en",
    "name": "Postal service / agency",
    "company": "Albion Royal Postal Services Ltd",
    "legalForm": "Ltd (private limited company; Royal Charter delivery agent)",
    "city": "Birmingham",
    "fleet": 14,
    "file": "29-postal-agency.en.json",
    "sizeKB": 6382.0,
    "total": 285,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 14,
      "trackedObjects": 12,
      "drivers": 12,
      "driverCertifications": 18,
      "customers": 8,
      "locations": 16,
      "workOrders": 14,
      "routes": 14,
      "stops": 38,
      "assignments": 14,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 7,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "29",
    "key": "postal-agency",
    "loc": "sv",
    "name": "Postal service / agency",
    "company": "Sverigeposten Logistik AB",
    "legalForm": "AB",
    "city": "Norrköping",
    "fleet": 13,
    "file": "29-postal-agency.sv.json",
    "sizeKB": 6565.0,
    "total": 258,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 13,
      "trackedObjects": 12,
      "drivers": 10,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 13,
      "stops": 31,
      "assignments": 12,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "30",
    "key": "military-defense-logistics",
    "loc": "de",
    "name": "Military & defense logistics",
    "company": "Adlerschild Wehrlogistik & Materialerhaltung GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 9,
    "file": "30-military-defense-logistics.de.json",
    "sizeKB": 6203.0,
    "total": 239,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 14,
      "telemetryReadings": 42,
      "events": 16,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "30",
    "key": "military-defense-logistics",
    "loc": "en",
    "name": "Military & defense logistics",
    "company": "Sentinel Defence Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Bristol",
    "fleet": 11,
    "file": "30-military-defense-logistics.en.json",
    "sizeKB": 7295.0,
    "total": 253,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 46,
      "events": 17,
      "notes": 13,
      "documents": 17,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "30",
    "key": "military-defense-logistics",
    "loc": "sv",
    "name": "Military & defense logistics",
    "company": "Nordfront Försvarslogistik AB",
    "legalForm": "AB",
    "city": "Örebro",
    "fleet": 14,
    "file": "30-military-defense-logistics.sv.json",
    "sizeKB": 6122.0,
    "total": 254,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 35,
      "assignments": 13,
      "telemetryReadings": 48,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "31",
    "key": "pharma-meddevice",
    "loc": "de",
    "name": "Pharmaceutical & medical-device",
    "company": "PharmaLog Rhein-Main Arzneimittellogistik GmbH",
    "legalForm": "GmbH",
    "city": "Frankfurt am Main",
    "fleet": 9,
    "file": "31-pharma-meddevice.de.json",
    "sizeKB": 8907.0,
    "total": 287,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 9,
      "trackedObjects": 9,
      "drivers": 10,
      "driverCertifications": 23,
      "customers": 8,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 36,
      "assignments": 13,
      "telemetryReadings": 49,
      "events": 19,
      "notes": 14,
      "documents": 22,
      "fieldDefinitions": 15,
      "inspections": 6,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "31",
    "key": "pharma-meddevice",
    "loc": "en",
    "name": "Pharmaceutical & medical-device",
    "company": "Caldermere Pharma Logistics Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 38,
    "file": "31-pharma-meddevice.en.json",
    "sizeKB": 6185.0,
    "total": 245,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 8,
      "trackedObjects": 7,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 12,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 16,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "31",
    "key": "pharma-meddevice",
    "loc": "sv",
    "name": "Pharmaceutical & medical-device",
    "company": "Nordström Pharma Logistik AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 8,
    "file": "31-pharma-meddevice.sv.json",
    "sizeKB": 5545.0,
    "total": 264,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 8,
      "trackedObjects": 9,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 8,
      "locations": 13,
      "workOrders": 14,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 52,
      "events": 17,
      "notes": 14,
      "documents": 15,
      "fieldDefinitions": 13,
      "inspections": 7,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "32",
    "key": "pool-company-cars",
    "loc": "de",
    "name": "Sales pool / company cars",
    "company": "RheinMain Außendienst & Fuhrparkservice GmbH",
    "legalForm": "GmbH",
    "city": "Frankfurt am Main",
    "fleet": 11,
    "file": "32-pool-company-cars.de.json",
    "sizeKB": 6020.0,
    "total": 264,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 7,
      "drivers": 10,
      "driverCertifications": 16,
      "customers": 7,
      "locations": 11,
      "workOrders": 13,
      "routes": 12,
      "stops": 32,
      "assignments": 13,
      "telemetryReadings": 52,
      "events": 18,
      "notes": 14,
      "documents": 15,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "32",
    "key": "pool-company-cars",
    "loc": "en",
    "name": "Sales pool / company cars",
    "company": "Meridian Field Solutions Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 12,
    "file": "32-pool-company-cars.en.json",
    "sizeKB": 6722.0,
    "total": 253,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 12,
      "trackedObjects": 7,
      "drivers": 9,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 12,
      "workOrders": 13,
      "routes": 14,
      "stops": 31,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "32",
    "key": "pool-company-cars",
    "loc": "sv",
    "name": "Sales pool / company cars",
    "company": "Bergström Vagnpark & Poolbilar AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 12,
    "file": "32-pool-company-cars.sv.json",
    "sizeKB": 5554.0,
    "total": 261,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 12,
      "trackedObjects": 8,
      "drivers": 10,
      "driverCertifications": 13,
      "customers": 6,
      "locations": 12,
      "workOrders": 14,
      "routes": 13,
      "stops": 36,
      "assignments": 13,
      "telemetryReadings": 49,
      "events": 18,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "33",
    "key": "car-dealership",
    "loc": "de",
    "name": "Car dealership (demo/loaner)",
    "company": "Autohaus Sterndorf GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 14,
    "file": "33-car-dealership.de.json",
    "sizeKB": 5813.0,
    "total": 246,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 14,
      "trackedObjects": 7,
      "drivers": 9,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 42,
      "events": 16,
      "notes": 13,
      "documents": 14,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "33",
    "key": "car-dealership",
    "loc": "en",
    "name": "Car dealership (demo/loaner)",
    "company": "Pennington Motor Group Ltd",
    "legalForm": "Ltd",
    "city": "Leeds",
    "fleet": 11,
    "file": "33-car-dealership.en.json",
    "sizeKB": 6979.0,
    "total": 240,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 11,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 9,
      "workOrders": 12,
      "routes": 13,
      "stops": 29,
      "assignments": 13,
      "telemetryReadings": 44,
      "events": 17,
      "notes": 13,
      "documents": 16,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "33",
    "key": "car-dealership",
    "loc": "sv",
    "name": "Car dealership (demo/loaner)",
    "company": "Lundqvist Bil & Motor AB",
    "legalForm": "AB",
    "city": "Jönköping",
    "fleet": 12,
    "file": "33-car-dealership.sv.json",
    "sizeKB": 6540.0,
    "total": 260,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 12,
      "trackedObjects": 8,
      "drivers": 10,
      "driverCertifications": 13,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 14,
      "stops": 28,
      "assignments": 14,
      "telemetryReadings": 49,
      "events": 18,
      "notes": 14,
      "documents": 16,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "34",
    "key": "carshare-micromobility",
    "loc": "de",
    "name": "Car-share / micromobility",
    "company": "StadtFlitzer Mobility GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 12,
    "file": "34-carshare-micromobility.de.json",
    "sizeKB": 7757.0,
    "total": 262,
    "counts": {
      "vehicleTypes": 6,
      "vehicles": 12,
      "trackedObjects": 8,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 11,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 52,
      "events": 17,
      "notes": 14,
      "documents": 17,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 8
    }
  },
  {
    "nn": "34",
    "key": "carshare-micromobility",
    "loc": "en",
    "name": "Car-share / micromobility",
    "company": "Veloport Mobility Ltd",
    "legalForm": "Ltd",
    "city": "Manchester",
    "fleet": 12,
    "file": "34-carshare-micromobility.en.json",
    "sizeKB": 6558.0,
    "total": 258,
    "counts": {
      "vehicleTypes": 5,
      "vehicles": 12,
      "trackedObjects": 11,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 31,
      "assignments": 13,
      "telemetryReadings": 55,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "34",
    "key": "carshare-micromobility",
    "loc": "sv",
    "name": "Car-share / micromobility",
    "company": "SvevaGo Delningsmobilitet AB",
    "legalForm": "AB",
    "city": "Stockholm",
    "fleet": 9,
    "file": "34-carshare-micromobility.sv.json",
    "sizeKB": 6575.0,
    "total": 247,
    "counts": {
      "vehicleTypes": 4,
      "vehicles": 9,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 12,
      "customers": 7,
      "locations": 12,
      "workOrders": 14,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 45,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "35",
    "key": "tool-rental",
    "loc": "de",
    "name": "Equipment & tool rental",
    "company": "MietWerk Geräte- und Werkzeugvermietung GmbH",
    "legalForm": "GmbH",
    "city": "München",
    "fleet": 12,
    "file": "35-tool-rental.de.json",
    "sizeKB": 7484.0,
    "total": 263,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 12,
      "trackedObjects": 10,
      "drivers": 8,
      "driverCertifications": 14,
      "customers": 6,
      "locations": 11,
      "workOrders": 13,
      "routes": 14,
      "stops": 32,
      "assignments": 14,
      "telemetryReadings": 44,
      "events": 18,
      "notes": 14,
      "documents": 18,
      "fieldDefinitions": 13,
      "inspections": 6,
      "maintenanceJobs": 9
    }
  },
  {
    "nn": "35",
    "key": "tool-rental",
    "loc": "en",
    "name": "Equipment & tool rental",
    "company": "Kerb & Crane Tool Hire Ltd",
    "legalForm": "Ltd",
    "city": "Birmingham",
    "fleet": 7,
    "file": "35-tool-rental.en.json",
    "sizeKB": 6091.0,
    "total": 235,
    "counts": {
      "vehicleTypes": 7,
      "vehicles": 6,
      "trackedObjects": 7,
      "drivers": 7,
      "driverCertifications": 12,
      "customers": 6,
      "locations": 9,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 42,
      "events": 17,
      "notes": 13,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  },
  {
    "nn": "35",
    "key": "tool-rental",
    "loc": "sv",
    "name": "Equipment & tool rental",
    "company": "Hyrcenter Mälardalen AB",
    "legalForm": "AB",
    "city": "Västerås",
    "fleet": 9,
    "file": "35-tool-rental.sv.json",
    "sizeKB": 6757.0,
    "total": 255,
    "counts": {
      "vehicleTypes": 10,
      "vehicles": 10,
      "trackedObjects": 8,
      "drivers": 7,
      "driverCertifications": 14,
      "customers": 7,
      "locations": 10,
      "workOrders": 13,
      "routes": 13,
      "stops": 30,
      "assignments": 13,
      "telemetryReadings": 49,
      "events": 17,
      "notes": 14,
      "documents": 15,
      "fieldDefinitions": 12,
      "inspections": 6,
      "maintenanceJobs": 7
    }
  }
]
;
